//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boss
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Boss()
        {
            this.Job = new HashSet<Job>();
        }
    
        public int BossId { get; set; }
        public string BossName { get; set; }
        public string BossTel { get; set; }
        public string BossMail { get; set; }
        public Nullable<int> BossSubId { get; set; }
        public string BossPassword { get; set; }
        public Nullable<bool> BossIsConnection { get; set; }
        public Nullable<int> BossCompanyId { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual SubjectJob SubjectJob { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Job> Job { get; set; }
    }
}
