//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IdialEntities3 : DbContext
    {
        public IdialEntities3()
            : base("name=IdialEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area> Area { get; set; }
        public virtual DbSet<Boss> Boss { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<Cv> Cv { get; set; }
        public virtual DbSet<Job> Job { get; set; }
        public virtual DbSet<OutNet> OutNet { get; set; }
        public virtual DbSet<Part> Part { get; set; }
        public virtual DbSet<PutInJob> PutInJob { get; set; }
        public virtual DbSet<Question> Question { get; set; }
        public virtual DbSet<Rav> Rav { get; set; }
        public virtual DbSet<Recomend> Recomend { get; set; }
        public virtual DbSet<Request> Request { get; set; }
        public virtual DbSet<Sign> Sign { get; set; }
        public virtual DbSet<SubjectJob> SubjectJob { get; set; }
        public virtual DbSet<Survey> Survey { get; set; }
        public virtual DbSet<TopicQuestion> TopicQuestion { get; set; }
        public virtual DbSet<TypeConnect> TypeConnect { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Workspace> Workspace { get; set; }
        public virtual DbSet<Adv> Adv { get; set; }
        public virtual DbSet<Count> Count { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
