//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int ReqId { get; set; }
        public Nullable<int> ReqUserId { get; set; }
        public string ReqContents { get; set; }
        public Nullable<int> ReqTypeConectId { get; set; }
    
        public virtual TypeConnect TypeConnect { get; set; }
        public virtual User User { get; set; }
    }
}
