//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Survey
    {
        public int SurveyId { get; set; }
        public Nullable<int> SurveySubLearnId { get; set; }
        public Nullable<bool> SurveyIsWork { get; set; }
        public Nullable<int> SurveySubTodayId { get; set; }
        public string SurveySeminar { get; set; }
        public string SurveySubLearnedTxt { get; set; }
        public string SurveySubTodayTxt { get; set; }
    
        public virtual SubjectJob SubjectJob { get; set; }
        public virtual SubjectJob SubjectJob1 { get; set; }
    }
}
