//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adv
    {
        public int AdvId { get; set; }
        public Nullable<bool> AdvStatus { get; set; }
        public string AdvLink { get; set; }
        public string AdvTitle { get; set; }
        public string AdvContent { get; set; }
        public string AdvMail { get; set; }
        public string AdvPhone { get; set; }
        public Nullable<int> CountUsers { get; set; }
    }
}
