//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recomend
    {
        public int RecomendId { get; set; }
        public Nullable<int> RecomendUserId { get; set; }
        public Nullable<int> RecomemdCompanyId { get; set; }
        public string RecomendInfo { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual User User { get; set; }
    }
}
