//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sign
    {
        public int SignId { get; set; }
        public Nullable<int> SignJobId { get; set; }
        public Nullable<int> SignUserId { get; set; }
        public Nullable<System.DateTime> SignDate { get; set; }
        public Nullable<bool> SignStatusSend { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual User User { get; set; }
    }
}
